# config.yaml
optimizer: AdamW
epochs: 50
batch_size: 16
imgsz: 640
learning_rate: 0.002
momentum: 0.937
weight_decay: 0.0005
augmentation:
  flip_lr: 0.5
  mosaic: 1.0
  mixup: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 5
  translate: 0.1
  scale: 0.5
