#
# Flowmotion
# CI/CD
# Backend CI
#

name: Flowmotion Backend Deployment
on:
  push: {}
permissions:
  # needed to push docker images to GHCR
  packages: write
jobs:
  deploy-backend:
    name: Deploy Flowmotion Backend on Google Cloud
    defaults:
      run:
        working-directory: backend
    env:
      IMAGE: ghcr.io/zhixin18/flowmotion/backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # publish backend container
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Flowmotion Backend container tags
        id: backend-meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: ${{ env.IMAGE }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and Push Flowmotion Backend container
        id: backend-build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: backend
          tags: ${{ steps.backend-meta.outputs.tags }}
          labels: ${{ steps.backend-meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache,mode=max

      # deploy backend container
      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: Deploy Backend Container to GCP Cloud run
        run: |
          gcloud run deploy flowmotion-backend \
            --image asia-southeast1-docker.pkg.dev/flowmotion-4e268/ghcr/zhixin18/flowmotion/backend@${{ steps.backend-build.outputs.imageid }} \
            --platform managed \
            --region=asia-southeast1 \
            --allow-unauthenticated \
            --port 3000 \
            --cpu 1 \
            --memory 256Mi \
            --cpu-boost
