#
# Flowmotion
# CI/CD
# Backend CI
#

name: Flowmotion Backend CI/CD
on:
  push: {}
jobs:
  backend:
    strategy:
      fail-fast: false
      matrix:
        target: [lint, build, test]
    name: "${{ matrix.target }} Backend"
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # tests are dependent on SGT timezone to run correctly
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Singapore"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: "${{ matrix.target }} Backend"
        run: npm run ${{ matrix.target }}
