name: Flowmotion CI/CD

on:
  push: {}
  pull_request: {}

jobs:
  pipeline:
    strategy:
      fail-fast: false
      matrix: 
          target: [lint, test]
    name: "${{ matrix.target }} Pipeline"
    defaults:
      run:
        working-directory: pipeline
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"
          cache: "pip"

      - name: Install Pip dependencies
        run: pip install -r requirements.txt

      - name: Reformat code with black
        run: black .

      - name: "${{ matrix.target }} Pipeline"
        run: "make ${{ matrix.target }}"

      # Optional: Auto-commit changes if black reformats the files
      - name: Commit and push changes if reformatted
        if: ${{ matrix.target == 'lint' }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git diff --exit-code || (git add . && git commit -m "Reformatted code with black" && git push)

