#
# Flowmotion
# Pipeline
# Scheduled Workflow
#

name: Flowmotion Pipeline
on:
  schedule:
    # run every 10 minutes
    - cron: "*/10 * * * *"
permissions:
  # needed to push docker images to GHCR
  packages: write
jobs:
  run-pipeline:
    env:
      ORSM_IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
    runs-on: ubuntu-22.04
    steps:
      # setup dependencies & source code
      - name: Install osmium CLI with APT
        run: sudo apt-get update && sudo apt-get install -y osmium-tool

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"
          # cache pip dependencies
          cache: "pip"

      - name: Install Pip dependencies
        run: pip install -r pipeline/requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      # run congestion model to rate congestion points
      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: Run Congestion Model Pipeline
        run: python pipeline/pipeline.py

      # download & customize OSM map data with congestion ratings
      - name: Cache OSM Map Data
        id: cache-map
        uses: actions/cache@v3
        with:
          path: map.osm.pbf
          key: map-${{ hashFiles('.github/workflows/pipeline.yaml') }}

      - name: Download & Extract OSM Map data
        if: ${{ steps.cache-map.outputs.cache-hit != 'true' }}
        run: |
          set -ex -o pipefail
          # download map data
          curl https://download.geofabrik.de/asia/malaysia-singapore-brunei-latest.osm.pbf -o map.osm.pbf 
          # limit map data to bounding box for singapore to speed up processing
          osmium extract --bbox=103.590088,1.210466,104.037094,1.475438 map_bbox.osm.pbf -o bbox.osm.pbf

      - name: Tag OSM Map Data with Congestion Ratings
        run: python pipeline/tag.py map_bbox.osm.pbf osrm/map_tagged.osm.pbf

      # publish OSRM container with custom congestion profile
      - name: Docker Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate OSRM container tags
        id: osrm-meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: ${{ env.ORSM_IMAGE }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and Push OSRM with Custom Congestion Profile
        uses: docker/build-push-action@v6
        with:
          push: true
          context: osrm
          tags: ${{ steps.orsm-meta.outputs.tags }}
          labels: ${{ steps.orms-meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.ORSM_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.ORSM_IMAGE }}:buildcache,mode=max
