#
# Flowmotion
# Pipeline
# Scheduled Workflow
#

name: Flowmotion Pipeline

on:
  schedule:
    # run every 10 minutes
    - cron: "*/10 * * * *"

jobs:
  run-pipeline:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: pipeline

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"
          cache: "pip"

      - name: Install Pip dependencies
        run: pip install -r requirements.txt 

      - name: Reformat code with black
        run: black .

      - name: Commit and push if code was reformatted
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git diff --exit-code || (git add . && git commit -m "Reformat code with black" && git push)
        # This step will commit and push the reformatted code if changes were made

      - name: Check formatting with black
        run: black --check .

      - name: Run Tests
        run: pytest

      - name: Run Pipeline
        run: python pipeline.py


