#
# Flowmotion
# CI/CD Pipeline
# Pipeline
#

name: Flowmotion Pipeline CI/CD 
on:
  push: 
    paths:
      - .github/workflows/pipeline-ci.yaml
      - "pipeline/**"
jobs:
  pipeline:
    strategy:
      fail-fast: false
      matrix:
        target: [lint, test]
    name: "${{ matrix.target }} Pipeline"
    defaults:
      run:
        working-directory: pipeline
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"
          # cache pip dependencies
          cache: "pip"
      - name: Install Pip dependencies
        run: pip install -r requirements.txt
      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
      - name: "${{ matrix.target }} Pipeline"
        run: "make ${{ matrix.target }}"
